[project]
name = "file-management"
version = "0.1.0"
description = "file management backend service"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.121.1",
]
